workflows:
  android-workflow:
    name: ShadowLink Build
    max_build_duration: 30
    scripts:
      - name: Setup
        script: |
          flutter create --platforms android .
          flutter pub get
      - name: Build
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
