workflows:
  android-workflow:
    name: ShadowLink Build
    max_build_duration: 30
    scripts:
      - name: Reparation dossier Android
        script: flutter create . --platforms=android
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
