workflows:
  android-workflow:
    name: ShadowLink Build
    instance_type: linux_small
    scripts:
      - name: Create Android Folder
        script: flutter create . --platforms=android
      - name: Get Packages
        script: flutter packages pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
