workflows:
  android-workflow:
    name: ShadowLink Build
    instance_type: linux_small
    scripts:
      - name: Generation du dossier Android
        script: flutter create . --platforms=android
      - name: Installation des paquets
        script: flutter packages pub get
      - name: Compilation APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
