workflows:
  android-workflow:
    name: ShadowLink
    instance_type: linux_small
    scripts:
      - flutter packages pub get
      - flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
