workflows:
  android-workflow:
    name: ShadowLink Build
    instance_type: linux_small
    scripts:
      - name: Force Android Project Generation
        script: |
          # Cette commande va recréer la structure Android proprement
          flutter create --platforms android .
      - name: Install Dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --debug --target-platform android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
