    scripts:
      - name: Reparation dossier Android
        script: flutter create . --platforms=android
      - name: Nettoyage
        script: flutter clean
      - name: Installation dependances
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug --verbose
